name: Build & Publish Proxies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ship-proxy:
    name: Build SHIP Proxy Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build SHIP Proxy JAR
        run: mvn -f ship-proxy/pom.xml clean package -DskipTests

      - name: Build SHIP Proxy Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/ship-proxy:latest ./ship-proxy

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SHIP Proxy Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/ship-proxy:latest

  build-offshore-proxy:
    name: Build OFFSHORE Proxy Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build OFFSHORE Proxy JAR
        run: mvn -f offshore-proxy/pom.xml clean package -DskipTests

      - name: Build OFFSHORE Proxy Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/offshore-proxy:latest ./offshore-proxy

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push OFFSHORE Proxy Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/offshore-proxy:latest

