name: Build & Publish SHIP and OFFSHORE Proxies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ship-proxy:
    name: Build SHIP Proxy Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build SHIP Proxy JAR
        run: mvn -f shipproxy-monorepo/proxy-client/pom.xml clean package -DskipTests

      - name: Build SHIP Proxy Docker Image
        run: docker build -t ghcr.io/994450/ship-proxy:latest ./shipproxy-monorepo/proxy-client

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SHIP Proxy Docker Image
        run: docker push ghcr.io/994450/ship-proxy:latest

  build-offshore-proxy:
    name: Build OFFSHORE Proxy Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build OFFSHORE Proxy JAR
        run: mvn -f shipproxy-monorepo/proxy-server/pom.xml clean package -DskipTests

      - name: Build OFFSHORE Proxy Docker Image
        run: docker build -t ghcr.io/994450/offshore-proxy:latest ./shipproxy-monorepo/proxy-server

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push OFFSHORE Proxy Docker Image
        run: docker push ghcr.io/994450/offshore-proxy:latest
